# Generated by Django 5.1.7 on 2025-03-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        choices=[("APPARTEMENT", "Appartement"), ("MAISON", "Maison")],
                        max_length=20,
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                ("loyer_mensuel", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_caution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant de la caution",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParametresSCI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_sci",
                    models.CharField(
                        default="SCI les Jonquilles",
                        max_length=100,
                        verbose_name="Nom de la SCI",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        default="24 rue des jardins de la Somme",
                        max_length=200,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        default="80800", max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        default="CORBIE", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "representants",
                    models.CharField(
                        default="Gisèle et Jean BULTEL",
                        max_length=200,
                        verbose_name="Représentants",
                    ),
                ),
                (
                    "titre_representants",
                    models.CharField(
                        default="Co-gérants",
                        max_length=100,
                        verbose_name="Titre des représentants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres SCI",
                "verbose_name_plural": "Paramètres SCI",
            },
        ),
        migrations.CreateModel(
            name="SCI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom de la SCI")),
                ("adresse", models.CharField(max_length=200, verbose_name="Adresse")),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "representants",
                    models.CharField(max_length=200, verbose_name="Représentants"),
                ),
                (
                    "titre_representants",
                    models.CharField(
                        max_length=100, verbose_name="Titre des représentants"
                    ),
                ),
            ],
            options={
                "verbose_name": "SCI",
                "verbose_name_plural": "SCIs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "categorie",
                    models.CharField(
                        choices=[("RECETTE", "Recette"), ("DEPENSE", "Dépense")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_entree", models.DateField(verbose_name="Date d'entrée")),
                (
                    "date_sortie",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de sortie"
                    ),
                ),
                (
                    "caution_versee",
                    models.BooleanField(default=False, verbose_name="Caution versée"),
                ),
                (
                    "montant_caution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant de la caution",
                    ),
                ),
                (
                    "date_versement_caution",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de versement de la caution",
                    ),
                ),
                (
                    "date_restitution_caution",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de restitution de la caution",
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locataires",
                        to="principale.bien",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bien",
            name="sci",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biens",
                to="principale.sci",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "mois_concerne",
                    models.DateField(
                        blank=True,
                        help_text="Mois et année concernés par cette transaction",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="principale.bien",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="principale.locataire",
                    ),
                ),
                (
                    "sci",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="principale.sci",
                    ),
                ),
                (
                    "type_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="principale.typetransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParametresComptables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                (
                    "solde_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "compte_courant_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sci",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="principale.sci",
                    ),
                ),
            ],
            options={
                "unique_together": {("sci", "annee")},
            },
        ),
    ]
