# Generated by Django 5.1.7 on 2025-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0002_update_parametres_comptables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametressci",
            options={
                "ordering": ["nom_sci"],
                "permissions": [
                    ("view_all_sci", "Can view all SCIs"),
                    ("manage_sci", "Can manage SCI properties"),
                ],
                "verbose_name": "SCI",
                "verbose_name_plural": "SCIs",
            },
        ),
        migrations.AlterField(
            model_name="bien",
            name="type_bien",
            field=models.CharField(
                choices=[("LOGEMENT", "Logement"), ("PARKING", "Parking")],
                max_length=20,
            ),
        ),
    ]
