# Generated by Django 5.1.7 on 2025-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0003_alter_parametressci_options_alter_bien_type_bien"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametressci",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("view_all_sci", "Can view all SCIs"),
                    ("manage_sci", "Can manage SCI properties"),
                ],
                "verbose_name": "SCI",
                "verbose_name_plural": "SCIs",
            },
        ),
        migrations.RemoveField(
            model_name="locataire",
            name="bien",
        ),
        migrations.AddField(
            model_name="locataire",
            name="biens",
            field=models.ManyToManyField(
                blank=True, related_name="locataires", to="principale.bien"
            ),
        ),
    ]
