# Generated by Django 5.1.7 on 2025-03-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "principale",
            "0004_alter_parametressci_options_remove_locataire_bien_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametressci",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("view_all_sci", "Can view all SCIs"),
                    ("manage_sci", "Can manage SCI properties"),
                ],
                "verbose_name": "Paramètres SCI",
                "verbose_name_plural": "Paramètres SCIs",
            },
        ),
    ]
