# Generated by Django 5.1.7 on 2025-03-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0005_alter_parametressci_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationBien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entree", models.DateField(verbose_name="Date d'entrée")),
                (
                    "date_sortie",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de sortie"
                    ),
                ),
                (
                    "montant_caution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant de la caution",
                    ),
                ),
                (
                    "date_versement_caution",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de versement de la caution",
                    ),
                ),
                (
                    "date_restitution_caution",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de restitution de la caution",
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="principale.bien",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="principale.locataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location de bien",
                "verbose_name_plural": "Locations de biens",
                "unique_together": {("locataire", "bien")},
            },
        ),
    ]
