# Generated by Django 5.1.7 on 2025-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0008_create_locationbien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locataire",
            name="date_entree",
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
    ]
