# Generated by Django 5.1.7 on 2025-03-25 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0009_alter_locataire_date_entree"),
    ]

    operations = [
        migrations.AddField(
            model_name="locataire",
            name="sci",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locataires",
                to="principale.sci",
            ),
        ),
    ]
