# Generated by Django 5.1.7 on 2025-03-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0010_locataire_sci"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locataire",
            name="date_entree",
        ),
        migrations.RemoveField(
            model_name="locataire",
            name="date_sortie",
        ),
    ]
