# Generated by Django 5.1.7 on 2025-03-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0011_remove_date_fields_from_locataire"),
    ]

    operations = [
        migrations.AddField(
            model_name="bien",
            name="montant_charges",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Montant des charges",
            ),
        ),
        migrations.AlterField(
            model_name="bien",
            name="loyer_mensuel",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Loyer hors charges"
            ),
        ),
        migrations.CreateModel(
            name="CommentaireCreance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_creance", models.CharField(max_length=50)),
                ("periode", models.CharField(max_length=50)),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="principale.bien",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="principale.locataire",
                    ),
                ),
                (
                    "sci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="principale.sci"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("sci", "locataire", "bien", "type_creance", "periode")
                },
            },
        ),
    ]
