# Generated by Django 5.1.7 on 2025-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0012_bien_montant_charges_alter_bien_loyer_mensuel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locataire",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Adresse"
            ),
        ),
        migrations.AddField(
            model_name="locataire",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AddField(
            model_name="locataire",
            name="telephone_portable",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Téléphone portable"
            ),
        ),
        migrations.AddField(
            model_name="locataire",
            name="ville",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville"
            ),
        ),
    ]
