# Generated by Django 5.1.7 on 2025-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0013_locataire_adresse_locataire_code_postal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrescomptables",
            name="solde_final",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bien",
            name="type_bien",
            field=models.CharField(
                choices=[
                    ("LOGEMENT", "Logement"),
                    ("PARKING", "Parking"),
                    ("COMMERCE", "Commerce"),
                ],
                max_length=20,
            ),
        ),
    ]
