# Generated by Django 5.1.7 on 2026-01-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0014_parametrescomptables_solde_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bien",
            name="type_bien",
            field=models.CharField(
                choices=[
                    ("LOGEMENT", "Logement"),
                    ("PARKING", "Parking"),
                    ("COMMERCE", "Commerce"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bien",
            name="ville",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="locationbien",
            name="date_entree",
            field=models.DateField(db_index=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name="locationbien",
            name="date_sortie",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Date de sortie"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="mois_concerne",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Mois et année concernés par cette transaction",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="bien",
            index=models.Index(
                fields=["sci", "type_bien"], name="principale__sci_id_d4c272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bien",
            index=models.Index(fields=["ville"], name="principale__ville_1c98db_idx"),
        ),
        migrations.AddIndex(
            model_name="locationbien",
            index=models.Index(
                fields=["bien", "date_sortie"], name="principale__bien_id_ef5529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationbien",
            index=models.Index(
                fields=["locataire", "date_sortie"],
                name="principale__locatai_3f1936_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["sci", "date"], name="principale__sci_id_99c3ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["sci", "-date"], name="principale__sci_id_cbe1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["bien", "date"], name="principale__bien_id_26ebbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["locataire", "date"], name="principale__locatai_a1f904_idx"
            ),
        ),
    ]
