# Generated by Django 5.1.7 on 2026-03-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0015_alter_bien_type_bien_alter_bien_ville_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MontantOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "montant_attendu",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant attendu"
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="montants_om",
                        to="principale.bien",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="montants_om",
                        to="principale.locataire",
                    ),
                ),
                (
                    "sci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="montants_om",
                        to="principale.sci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Montant OM",
                "verbose_name_plural": "Montants OM",
                "ordering": ["-annee", "locataire__nom"],
                "unique_together": {("locataire", "bien", "annee")},
            },
        ),
    ]
