# Generated by Django 5.2.14 on 2026-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0016_montantom"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationbien",
            name="montant_charges_premier_mois",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Charges 1er mois (prorata convenu)",
            ),
        ),
        migrations.AddField(
            model_name="locationbien",
            name="montant_loyer_premier_mois",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Loyer 1er mois (prorata convenu)",
            ),
        ),
    ]
