# Generated by Django 5.1.7 on 2026-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0017_add_prorata_premier_mois_locationbien"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationbien",
            name="commentaire_report_anterieur",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Commentaire sur le report antérieur",
            ),
        ),
        migrations.AddField(
            model_name="locationbien",
            name="solde_report_anterieur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Positif = trop-perçu (crédit), négatif = dette",
                max_digits=10,
                null=True,
                verbose_name="Report de solde antérieur à 2025",
            ),
        ),
    ]
