# Generated by Django 5.1.7 on 2026-07-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0018_locationbien_commentaire_report_anterieur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionLoyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                (
                    "nouveau_loyer",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Nouveau loyer hors charges",
                    ),
                ),
                (
                    "nouvelles_charges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Nouvelles charges",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions_loyer",
                        to="principale.locationbien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Révision de loyer",
                "verbose_name_plural": "Révisions de loyer",
                "ordering": ["date_effet"],
            },
        ),
    ]
