# Generated by Django 5.1.7 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principale", "0019_revisionloyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationbien",
            name="date_cloture_manuelle",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de clôture manuelle",
                help_text="Renseignée quand la créance restante (positive ou négative) est volontairement clôturée sans être soldée à 0",
            ),
        ),
        migrations.AddField(
            model_name="locationbien",
            name="commentaire_cloture",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Commentaire sur la clôture",
            ),
        ),
    ]
