"""
Django settings for gestion_locations project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Déterminer si nous sommes en production (sur PythonAnywhere)
# Vous pouvez également définir une variable d'environnement DJANGO_PRODUCTION=True
IS_PYTHONANYWHERE = 'PYTHONANYWHERE_DOMAIN' in os.environ

# SECURITY WARNING: keep the secret key used in production secret!
# En production, utilisez une variable d'environnement pour la clé secrète
if IS_PYTHONANYWHERE:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-k#w%nmt^=b=ajzsjxi!@01*bxtpz=5lujhr=0as2k$^wgs%e$k')
else:
    SECRET_KEY = 'django-insecure-k#w%nmt^=b=ajzsjxi!@01*bxtpz=5lujhr=0as2k$^wgs%e$k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Liste des hôtes autorisés
if IS_PYTHONANYWHERE:
    ALLOWED_HOSTS = ['Davidbenloulou.pythonanywhere.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'principale',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'principale.middleware.SCIMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_locations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Ajout du context processor pour les infos de la SCI
                'principale.context_processors.sci_info',
                'principale.context_processors.sci_context',
            ],
            'builtins': ['principale.templatetags.montant_filters'],
        },
    },
]

WSGI_APPLICATION = 'gestion_locations.wsgi.application'

# Database configuration
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'  # Code de langue français
TIME_ZONE = 'Europe/Paris'  # Fuseau horaire français
USE_I18N = True  # Activer l'internationalisation
USE_L10N = True  # Activer la localisation
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Dossiers supplémentaires où Django cherchera les fichiers statiques
STATICFILES_DIRS = [
    BASE_DIR / "principale" / "static",
]

# Dossier où les fichiers statiques seront collectés lors du déploiement
STATIC_ROOT = BASE_DIR / "staticfiles"

# Configuration de sécurité pour la production
if IS_PYTHONANYWHERE:
    # Force HTTPS
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

LOGIN_REQUIRED_IGNORE_VIEW_NAMES = ['dashboard', 'liste_biens', 'detail_bien', 'liste_locataires', 'detail_locataire', 'liste_transactions', 'detail_transaction', 'etat_paiements', 'bilan_comptable_detaille', 'loyers_manquants', 'changer_sci']
LOGIN_URL = '/'